### ISSUE TITLE
Remove Kubernetes specific code

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skydns#116]
Kubernetes uses a bespoke skydns-kubernetes bridge created by @thockin

**Comment by thockin** [comment]
I think it's cleaner that way, but please don't let me dictate how your project should behave :)

**Comment by smarterclayton** [comment]
On this issue - I had floated the idea with Tim that for efficiency at scale I really want to back a subset of  SkyDNS queries by calling directly to the Kube service API, rather than having to duplicate data from each service into a parallel record.  Currently the majority of the queries performed in server.go could be done directly via a single API call with the exception of reverse lookup - but eventually we'll have that as well once we have better storage.  In the vein of using SkyDNS as a library, if there was an interface for the `func (s *server) *Records(q dns.Question, name string)` methods that had etcd as a default implementation, it would be possible to increase the efficiency of our store by wrapping the underlying interface with a "lookup in destination X first, then in etcd" wrapper.  

I realize this is not a core SkyDNS use case, but when we start looking at thousands of active services in OpenShift it'd be desirable for us to do a bit of work to answer queries directly against Kube and then delegate to the etcd store for anything that is not covered to save the write amplification of service changes back to etcd (likely the same one storing kube data).  Would there be an objection to `Server` having a `Query` interface passed to it with a default `EtcdQuery` implementation?

**Comment by thockin** [comment]
I don't want skyDNS having a bunch of kubernetes logic built-in, at least
not while so much is still in flux.  If we can keep it cleanly split, I'd
be happy.

**Comment by smarterclayton** [comment]
I agree - the approach I'm considering for Openshift is that I want the DNS resolver to live with our master (just like all other controllers), and be skydns as a library pointing to Kube, with a fallback to etcd.  The "pointing at Kube" bit is not part of skydns - it's just a wrapper coming from our codebase.

**Comment by miekg** [comment]
There is a long standing comment in the code to make getting the records an interface and implement multiple backends.

In think we're better off wrapping `get` in `client.go` in an interface as that's only thing that actually talks to a backend. We also are able to store config in the backend, so something like

```
Records(...) []msg.Service
Config(...) *server.Config
```

Could be the interface.

**Comment by miekg** [comment]
So (pondered some more during my commute), what I will do it a define a `Getter` interface, and make a `NewServer(..., g Getter) *Server` that can be used.

**Comment by smarterclayton** [comment]
Whatever works for you guy - I'm happy to help with tests and feedback.

----- Original Message -----

**Comment by smarterclayton** [comment]
Was going to start on this soon - I'll follow the NewServer(...) pattern you described when I prototype this on my end.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Remove Kubernetes spec..." ]
>Was going to start on this soon - I'll follow the NewServer(...) pattern you described when I prototype this on my end.

Ack. I did some work in the face branch, but got distracted.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
kubernetes code has been removed.
