### ISSUE TITLE
Random stops responding

### ISSUE THREAD

**Issue by etopian** [skynetservices/skydns#134]
I have noticied that SkyDNS2 after perhaps the machine is suspended randomly stops responding to queries and has to be restarted because it simply no longer resolves queries. I don't know how to go about debugging this issue, but I have noticed it more than once.

**Comment by miekg** [comment]
Without a lot more context and information this is impossible for me to fix.

**Comment by etopian** [comment]
Is there any way to turn on a logging system or debug log ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Random stops respondin..." ]
>Is there any way to turn on a logging system or debug log ?

You can log queries with the -verbose flag. Anything important will be logged
anyhow, so if there isn't any logging Skydns will just thing it is running fine.

One thing that just pops in my head right now: could it be related to caching?
I.e. skydns thinks it has something in the cache, but due to being suspended
something fishy happens there...
Or it may fail to re-connect to etcd - which might be even more likely, but OTOH
skydns will just requery.

I think you might need th' old tcpdump for this.

/Miek

--
Miek Gieben
