### ISSUE TITLE
What do I write to etcd to make reverse lookups work?

### ISSUE THREAD

**Issue by thockin** [skynetservices/skydns#154]
I can't seem to figure it out.

Given:

```
etcdctl set /skydns/local/kubernetes/ns/svc/pod1 '{"host":"1.1.1.1", "port":80}'
```

I want to do a lookup of 1.1.1.1 and get back pod1.svc.ns.kubernetes.local.  Support for reverse lookups seems to be in the code but I cannot figure out how to make it answer my query

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] What do I write to etcd to..." ]
>I can't seem to figure it out.

I've updated that section in the README a little.

>Given:
>
>```
>etcdctl set /skydns/local/kubernetes/ns/svc/pod1 '{"host":"1.1.1.1", "port":80}'
>```
>
>I want to do a lookup of 1.1.1.1 and get back pod1.svc.ns.kubernetes.local.
>Support for reverse lookups seems to be in the code but I cannot figure out how
>to make it answer my query

(using skydns.local here):

./etcdctl/etcdctl set /skydns/arpa/in-addr/1/1/1/1 '{"host":"pod1.svc.ns.skydns.local"}'

% dig -x 1.1.1.1 -p 1053 @localhost +noall +answer

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> -x 1.1.1.1 -p 1053 @localhost +noall +answer
;; global options: +cmd
1.1.1.1.in-addr.arpa.   3600    IN      PTR     pod1.svc.ns.skydns.local.

If you really want to have fun, use v6 addresses:

;c.4.7.e.e.a.e.f.f.f.1.9.c.3.0.f.0.0.0.0.0.0.0.0.0.0.e.7.1.0.a.2.ip6.arpa. IN PTR

/Miek

--
Miek Gieben

**Comment by celevra** [comment]
1.1.1.1 is a bad example :-) do i have to reverse the ip also?

so in the example 192.168.0.1 do i have todo
/skydns/arpa/in-addr/1/0/168/192 '{"host":"pod1.svc.ns.skydns.local"}'

**Comment by thockin** [comment]
since in-addr.arpa is already backwards, you want the IP FORWARDS, I think.

**Comment by celevra** [comment]
You are absolutely right, it was a dump question cause the docs show it really nice.

I deleted my comment but the e-mail notification from github was to fast :-D

Thanks fort he answer



Von: Tim Hockin [mailto:notifications@github.com]
Gesendet: Mittwoch, 11. Mai 2016 18:07
An: skynetservices/skydns <skydns@noreply.github.com>
Cc: Philipp Zeitschel <philipp@zeitschel.net>; Comment <comment@noreply.github.com>
Betreff: Re: [skynetservices/skydns] What do I write to etcd to make reverse lookups work? (#154)



since in-addr.arpa is already backwards, you want the IP FORWARDS, I think.
